version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:00"
    labels:
      - "norelease"
    groups:
      go.mod:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:00"
    labels:
      - "norelease"
