version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - cyclop
    - dogsled
    - durationcheck
    - err113
    - errcheck
    - errname
    - exhaustive
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - hugeParam
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
    godot:
      exclude:
        - '@(Given|When|Then|And|But) (.*)'
    gosec:
      excludes:
        - G115
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - localised
        - catalogue
    wsl:
      allow-assign-and-call: false
      force-case-trailing-whitespace: 0
      allow-cuddle-with-calls:
        - Lock
        - RLock
      allow-cuddle-with-rhs:
        - Unlock
        - RUnlock
      force-err-cuddling: true
      error-variable-names:
        - err
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/PaddleHQ/paddle-go-sdk)
        - prefix(github.com/PaddleHQ)
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
