// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddle

import "context"

// CheckoutDomainApprovalStatus: Approval status of this checkout domain. Checkout domains are created as `pending_review`. It can be `pending_review`, `approved`, `rejected`, `in_review`, or `action_required`.
type CheckoutDomainApprovalStatus string

const (
	CheckoutDomainApprovalStatusPendingReview  CheckoutDomainApprovalStatus = "pending_review"
	CheckoutDomainApprovalStatusApproved       CheckoutDomainApprovalStatus = "approved"
	CheckoutDomainApprovalStatusRejected       CheckoutDomainApprovalStatus = "rejected"
	CheckoutDomainApprovalStatusInReview       CheckoutDomainApprovalStatus = "in_review"
	CheckoutDomainApprovalStatusActionRequired CheckoutDomainApprovalStatus = "action_required"
)

// CheckoutDomainPaymentMethod: Payment method to verify. Currently only apple_pay is supported.
type CheckoutDomainPaymentMethod string

const (
	CheckoutDomainPaymentMethodApplePay CheckoutDomainPaymentMethod = "apple_pay"
)

// CheckoutDomainPaymentMethodVerificationStatus: Payment method verification status for this checkout domain.
type CheckoutDomainPaymentMethodVerificationStatus string

const (
	CheckoutDomainPaymentMethodVerificationStatusVerified   CheckoutDomainPaymentMethodVerificationStatus = "verified"
	CheckoutDomainPaymentMethodVerificationStatusUnverified CheckoutDomainPaymentMethodVerificationStatus = "unverified"
)

// CheckoutDomainApplePayVerification: Apple Pay verification status for this checkout domain.
type CheckoutDomainApplePayVerification struct {
	Status CheckoutDomainPaymentMethodVerificationStatus `json:"status,omitempty"`
}

// CheckoutDomainPaymentMethodVerification: Payment method verification status for this checkout domain.
type CheckoutDomainPaymentMethodVerification struct {
	ApplePay CheckoutDomainApplePayVerification `json:"apple_pay,omitempty"`
}

// CheckoutDomain: Represents a checkout domain entity.
type CheckoutDomain struct {
	ID                        string                                  `json:"id,omitempty"`
	Domain                    string                                  `json:"domain,omitempty"`
	Status                    CheckoutDomainApprovalStatus            `json:"status,omitempty"`
	PaymentMethodVerification CheckoutDomainPaymentMethodVerification `json:"payment_method_verification,omitempty"`
	CreatedAt                 string                                  `json:"created_at,omitempty"`
	UpdatedAt                 string                                  `json:"updated_at,omitempty"`
}

// CheckoutDomainsClient is a client for the Checkout domains resource.
type CheckoutDomainsClient struct {
	doer Doer
}

// ListCheckoutDomainsRequest is given as an input to ListCheckoutDomains.
type ListCheckoutDomainsRequest struct {
	// ID is a query parameter.
	// Return only the IDs specified. Use a comma-separated list to get multiple entities.
	ID []string `in:"query=id;omitempty" json:"-"`
	// After is a query parameter.
	// Return entities after the specified Paddle ID when working with paginated endpoints. Used in the `meta.pagination.next` URL in responses for list operations.
	After *string `in:"query=after;omitempty" json:"-"`
	// PerPage is a query parameter.
	/*
	   Set how many entities are returned per page. Paddle returns the maximum number of results if a number greater than the maximum is requested. Check `meta.pagination.per_page` in the response to see how many were returned.

	   Default: `50`; Maximum: `200`.
	*/
	PerPage *int `in:"query=per_page;omitempty" json:"-"`
	// Domain is a query parameter.
	// Filter results to include the specified fully qualified domain name (FQDN), its ancestors, and any of its subdomains. For example, if you provide `app.example.com`, the results include `app.example.com`, `example.com` and any subdomains such as `cool.app.example.com`.
	Domain *string `in:"query=domain;omitempty" json:"-"`
	// OrderBy is a query parameter.
	/*
	   Order returned entities by the specified field and direction (`[ASC]` or `[DESC]`). For example, `?order_by=id[ASC]`.

	   Valid fields for ordering: `id`, `created_at`, and `updated_at`.
	*/
	OrderBy *string `in:"query=order_by;omitempty" json:"-"`
	// Status is a query parameter.
	// Return entities that match the specified status. Use a comma-separated list to specify multiple status values.
	Status []string `in:"query=status;omitempty" json:"-"`
}

// ListCheckoutDomains performs the GET operation on a Checkout domains resource.
func (c *CheckoutDomainsClient) ListCheckoutDomains(ctx context.Context, req *ListCheckoutDomainsRequest) (res *Collection[*CheckoutDomain], err error) {
	if err := c.doer.Do(ctx, "GET", "/checkout-domains", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetCheckoutDomainRequest is given as an input to GetCheckoutDomain.
type GetCheckoutDomainRequest struct {
	// URL path parameters.
	DomainID string `in:"path=domain_id" json:"-"`
}

// GetCheckoutDomain performs the GET operation on a Checkout domains resource.
func (c *CheckoutDomainsClient) GetCheckoutDomain(ctx context.Context, req *GetCheckoutDomainRequest) (res *CheckoutDomain, err error) {
	if err := c.doer.Do(ctx, "GET", "/checkout-domains/{domain_id}", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// DeleteCheckoutDomainRequest is given as an input to DeleteCheckoutDomain.
type DeleteCheckoutDomainRequest struct {
	// URL path parameters.
	DomainID string `in:"path=domain_id" json:"-"`
}

// DeleteCheckoutDomain performs the DELETE operation on a Checkout domains resource.
func (c *CheckoutDomainsClient) DeleteCheckoutDomain(ctx context.Context, req *DeleteCheckoutDomainRequest) (err error) {
	return c.doer.Do(ctx, "DELETE", "/checkout-domains/{domain_id}", req, nil)
}

// VerifyCheckoutDomainPaymentMethodRequest is given as an input to VerifyCheckoutDomainPaymentMethod.
type VerifyCheckoutDomainPaymentMethodRequest struct {
	// URL path parameters.
	DomainID string `in:"path=domain_id" json:"-"`

	PaymentMethod CheckoutDomainPaymentMethod `json:"payment_method,omitempty"`
}

// VerifyCheckoutDomainPaymentMethod performs the POST operation on a Checkout domains resource.
func (c *CheckoutDomainsClient) VerifyCheckoutDomainPaymentMethod(ctx context.Context, req *VerifyCheckoutDomainPaymentMethodRequest) (res *CheckoutDomain, err error) {
	if err := c.doer.Do(ctx, "POST", "/checkout-domains/{domain_id}/verify-payment-method", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
