// Code generated by the Paddle SDK Generator; DO NOT EDIT.
package paddle

import (
	"context"

	paddleerr "github.com/PaddleHQ/paddle-go-sdk/v6/pkg/paddleerr"
)

// ErrCurrencyPrimaryBalanceInvalid represents a `currency_primary_balance_invalid` error.
// See https://developer.paddle.com/errors/currencies/currency_primary_balance_invalid for more information.
var ErrCurrencyPrimaryBalanceInvalid = &paddleerr.Error{
	Code: "currency_primary_balance_invalid",
	Type: paddleerr.ErrorTypeRequestError,
}

// ErrCurrencyCodeInvalid represents a `currency_code_invalid` error.
// See https://developer.paddle.com/errors/currencies/currency_code_invalid for more information.
var ErrCurrencyCodeInvalid = &paddleerr.Error{
	Code: "currency_code_invalid",
	Type: paddleerr.ErrorTypeRequestError,
}

// ErrCurrencyCodesInvalid represents a `currency_codes_invalid` error.
// See https://developer.paddle.com/errors/currencies/currency_codes_invalid for more information.
var ErrCurrencyCodesInvalid = &paddleerr.Error{
	Code: "currency_codes_invalid",
	Type: paddleerr.ErrorTypeRequestError,
}

// CurrencyDefinition: Metadata about a currency that Paddle supports.
type CurrencyDefinition struct {
	// Code: Three-letter ISO 4217 code for the currency.
	Code CurrencyCode `json:"code,omitempty"`
	// Name: Full name of the currency.
	Name string `json:"name,omitempty"`
	// DecimalPlaces: The number of decimal places in the common notation of the currency.
	DecimalPlaces int `json:"decimal_places,omitempty"`
	// CanBeBalance: Whether you can hold your balance in this currency. You can set your balance currency in the dashboard.
	CanBeBalance bool `json:"can_be_balance,omitempty"`
	// ApplicableCountries: Countries where this currency is used for automatic price conversion. Only includes countries that Paddle supports sales to. You can set up automatic currency conversion in the dashboard.
	ApplicableCountries []CountryCode `json:"applicable_countries,omitempty"`
	// MinimumPaymentAmount: Minimum charge for this currency in the lowest denomination for this currency, for example 10 USD = 1000 (cents). Payment can't be attempted for a transaction or checkout below this amount.
	MinimumPaymentAmount string `json:"minimum_payment_amount,omitempty"`
}

// CurrenciesClient is a client for the Currencies resource.
type CurrenciesClient struct {
	doer Doer
}

// ListCurrenciesRequest is given as an input to ListCurrencies.
type ListCurrenciesRequest struct{}

// ListCurrencies performs the GET operation on a Currencies resource.
func (c *CurrenciesClient) ListCurrencies(ctx context.Context, req *ListCurrenciesRequest) (res *Collection[*CurrencyDefinition], err error) {
	if err := c.doer.Do(ctx, "GET", "/currencies", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
