// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddle

import "context"

// EventTypesClient is a client for the Event types resource.
type EventTypesClient struct {
	doer Doer
}

// ListEventTypesRequest is given as an input to ListEventTypes.
type ListEventTypesRequest struct{}

// ListEventTypes performs the GET operation on a Event types resource.
func (c *EventTypesClient) ListEventTypes(ctx context.Context, req *ListEventTypesRequest) (res *Collection[*EventType], err error) {
	if err := c.doer.Do(ctx, "GET", "/event-types", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
