// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddle

import "context"

// MetricsTimeseriesMonthlyRecurringRevenueDatapoint: A single datapoint in a monthly recurring revenue metrics timeseries. Used by both MRR and MRR change endpoints.
type MetricsTimeseriesMonthlyRecurringRevenueDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Amount: Amount for this datapoint in the lowest denomination for a currency.
	Amount string `json:"amount,omitempty"`
}

// MetricsTimeseriesMonthlyRecurringRevenue: Monthly recurring revenue metrics timeseries with amount for each datapoint.
type MetricsTimeseriesMonthlyRecurringRevenue struct {
	// CurrencyCode: Supported three-letter ISO 4217 currency code for this metric. Returned in your primary balance currency, converted using the exchange rate at the time of each transaction. If your primary balance currency changes, amounts continue to be returned in the previous currency until the next payout period begins.
	CurrencyCode CurrencyCode `json:"currency_code,omitempty"`
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesMonthlyRecurringRevenueDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesActiveSubscribersDatapoint: A single datapoint in an active subscribers metrics timeseries.
type MetricsTimeseriesActiveSubscribersDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Count: Number of active subscribers for this datapoint.
	Count int `json:"count,omitempty"`
}

// MetricsTimeseriesActiveSubscribers: Active subscribers metrics timeseries with count for each datapoint.
type MetricsTimeseriesActiveSubscribers struct {
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesActiveSubscribersDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesMonthlyRecurringRevenueChange: Monthly recurring revenue change metrics timeseries with amount for each datapoint.
type MetricsTimeseriesMonthlyRecurringRevenueChange struct {
	// CurrencyCode: Supported three-letter ISO 4217 currency code for this metric. Returned in your primary balance currency, converted using the exchange rate at the time of each transaction. If your primary balance currency changes, amounts continue to be returned in the previous currency until the next payout period begins.
	CurrencyCode CurrencyCode `json:"currency_code,omitempty"`
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesMonthlyRecurringRevenueDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesRevenueDatapoint: A single datapoint in a revenue metrics timeseries.
type MetricsTimeseriesRevenueDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Amount: Amount for this datapoint in the lowest denomination for a currency.
	Amount string `json:"amount,omitempty"`
	// Count: Number of transactions for this datapoint.
	Count int `json:"count,omitempty"`
}

// MetricsTimeseriesRevenue: Revenue metrics timeseries with amount and transaction count for each datapoint.
type MetricsTimeseriesRevenue struct {
	// CurrencyCode: Supported three-letter ISO 4217 currency code for this metric. Returned in your primary balance currency, converted using the current exchange rate.
	CurrencyCode CurrencyCode `json:"currency_code,omitempty"`
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesRevenueDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesRefundsDatapoint: A single datapoint in a refund metrics timeseries.
type MetricsTimeseriesRefundsDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Amount: Amount for this datapoint in the lowest denomination for a currency.
	Amount string `json:"amount,omitempty"`
}

// MetricsTimeseriesRefunds: Refund metrics timeseries with amount for each datapoint.
type MetricsTimeseriesRefunds struct {
	// CurrencyCode: Supported three-letter ISO 4217 currency code for this metric. Returned in your primary balance currency, converted using the current exchange rate.
	CurrencyCode CurrencyCode `json:"currency_code,omitempty"`
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesRefundsDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesChargebacksDatapoint: A single datapoint in a chargeback metrics timeseries.
type MetricsTimeseriesChargebacksDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Count: Number of chargebacks for this datapoint.
	Count int `json:"count,omitempty"`
}

// MetricsTimeseriesChargebacks: Chargeback metrics timeseries with count for each datapoint.
type MetricsTimeseriesChargebacks struct {
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesChargebacksDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsTimeseriesCheckoutConversionDatapoint: A single datapoint in a checkout conversion metrics timeseries.
type MetricsTimeseriesCheckoutConversionDatapoint struct {
	// Timestamp: RFC 3339 datetime string for this datapoint.
	Timestamp string `json:"timestamp,omitempty"`
	// Count: Total number of checkouts in this period.
	Count int `json:"count,omitempty"`
	// CompletedCount: Number of checkouts completed in this period.
	CompletedCount int `json:"completed_count,omitempty"`
	// Rate: Conversion rate for this period. Calculated by dividing `completed_count` by `count`.
	Rate string `json:"rate,omitempty"`
}

// MetricsTimeseriesCheckoutConversion: Checkout conversion metrics timeseries with count, completed count, and rate for each datapoint.
type MetricsTimeseriesCheckoutConversion struct {
	// Timeseries: Array of datapoints. Empty if `to` and `from` are the same.
	Timeseries []MetricsTimeseriesCheckoutConversionDatapoint `json:"timeseries,omitempty"`
	// StartsAt: RFC 3339 datetime string for when this timeseries starts (inclusive).
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string for when this timeseries ends (exclusive).
	EndsAt string `json:"ends_at,omitempty"`
	// Interval: Granularity for this timeseries.
	Interval Interval `json:"interval,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of the last successful data refresh for this metric.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// MetricsClient is a client for the Metrics resource.
type MetricsClient struct {
	doer Doer
}

// GetMetricsMonthlyRecurringRevenueRequest is given as an input to GetMetricsMonthlyRecurringRevenue.
type GetMetricsMonthlyRecurringRevenueRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsMonthlyRecurringRevenue performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsMonthlyRecurringRevenue(ctx context.Context, req *GetMetricsMonthlyRecurringRevenueRequest) (res *MetricsTimeseriesMonthlyRecurringRevenue, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/monthly-recurring-revenue", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsActiveSubscribersRequest is given as an input to GetMetricsActiveSubscribers.
type GetMetricsActiveSubscribersRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsActiveSubscribers performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsActiveSubscribers(ctx context.Context, req *GetMetricsActiveSubscribersRequest) (res *MetricsTimeseriesActiveSubscribers, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/active-subscribers", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsMonthlyRecurringRevenueChangeRequest is given as an input to GetMetricsMonthlyRecurringRevenueChange.
type GetMetricsMonthlyRecurringRevenueChangeRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsMonthlyRecurringRevenueChange performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsMonthlyRecurringRevenueChange(ctx context.Context, req *GetMetricsMonthlyRecurringRevenueChangeRequest) (res *MetricsTimeseriesMonthlyRecurringRevenueChange, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/monthly-recurring-revenue-change", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsRevenueRequest is given as an input to GetMetricsRevenue.
type GetMetricsRevenueRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsRevenue performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsRevenue(ctx context.Context, req *GetMetricsRevenueRequest) (res *MetricsTimeseriesRevenue, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/revenue", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsRefundsRequest is given as an input to GetMetricsRefunds.
type GetMetricsRefundsRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsRefunds performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsRefunds(ctx context.Context, req *GetMetricsRefundsRequest) (res *MetricsTimeseriesRefunds, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/refunds", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsChargebacksRequest is given as an input to GetMetricsChargebacks.
type GetMetricsChargebacksRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsChargebacks performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsChargebacks(ctx context.Context, req *GetMetricsChargebacksRequest) (res *MetricsTimeseriesChargebacks, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/chargebacks", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetMetricsCheckoutConversionRequest is given as an input to GetMetricsCheckoutConversion.
type GetMetricsCheckoutConversionRequest struct {
	// From is a query parameter.
	// Return data from a specific date. Pass an RFC 3339 full-date string. Interpreted at 00:00 UTC. Must be before or the same as `to`.
	From string `in:"query=from" json:"-"`
	// To is a query parameter.
	// Return data up to a specific date. Pass an RFC 3339 full-date string. Interpreted as 00:00 UTC. Must be after or the same as `from`.
	To string `in:"query=to" json:"-"`
}

// GetMetricsCheckoutConversion performs the GET operation on a Metrics resource.
func (c *MetricsClient) GetMetricsCheckoutConversion(ctx context.Context, req *GetMetricsCheckoutConversionRequest) (res *MetricsTimeseriesCheckoutConversion, err error) {
	if err := c.doer.Do(ctx, "GET", "/metrics/checkout-conversion", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
