// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddle

import (
	"context"
	"encoding/json"
)

// SubscriptionHistoryCanceledEffectiveFrom: When the subscription cancellation took effect.
type SubscriptionHistoryCanceledEffectiveFrom string

const (
	SubscriptionHistoryCanceledEffectiveFromImmediately       SubscriptionHistoryCanceledEffectiveFrom = "immediately"
	SubscriptionHistoryCanceledEffectiveFromNextBillingPeriod SubscriptionHistoryCanceledEffectiveFrom = "next_billing_period"
)

// SubscriptionHistoryOneOffChargeAppliedEffectiveFrom: When the customer was or will be billed for the one-off charge.
type SubscriptionHistoryOneOffChargeAppliedEffectiveFrom string

const (
	SubscriptionHistoryOneOffChargeAppliedEffectiveFromImmediately       SubscriptionHistoryOneOffChargeAppliedEffectiveFrom = "immediately"
	SubscriptionHistoryOneOffChargeAppliedEffectiveFromNextBillingPeriod SubscriptionHistoryOneOffChargeAppliedEffectiveFrom = "next_billing_period"
)

// SubscriptionHistoryPausedEffectiveFrom: When the subscription pause took effect.
type SubscriptionHistoryPausedEffectiveFrom string

const (
	SubscriptionHistoryPausedEffectiveFromImmediately       SubscriptionHistoryPausedEffectiveFrom = "immediately"
	SubscriptionHistoryPausedEffectiveFromNextBillingPeriod SubscriptionHistoryPausedEffectiveFrom = "next_billing_period"
)

// SubscriptionHistoryPaymentAttemptedOperation: The operation that triggered the failed payment attempt.
type SubscriptionHistoryPaymentAttemptedOperation string

const (
	SubscriptionHistoryPaymentAttemptedOperationSubscriptionUpdate       SubscriptionHistoryPaymentAttemptedOperation = "subscription_update"
	SubscriptionHistoryPaymentAttemptedOperationSubscriptionOneOffCharge SubscriptionHistoryPaymentAttemptedOperation = "subscription_one_off_charge"
	SubscriptionHistoryPaymentAttemptedOperationSubscriptionActivate     SubscriptionHistoryPaymentAttemptedOperation = "subscription_activate"
)

// SubscriptionHistoryReasonEnum: Why the entry was created. Only applicable to certain actions.
type SubscriptionHistoryReasonEnum string

const (
	SubscriptionHistoryReasonEnumCardlessTrialEnded SubscriptionHistoryReasonEnum = "cardless_trial_ended"
	SubscriptionHistoryReasonEnumImportIssue        SubscriptionHistoryReasonEnum = "import_issue"
	SubscriptionHistoryReasonEnumMissingConsent     SubscriptionHistoryReasonEnum = "missing_consent"
	SubscriptionHistoryReasonEnumSellerRequest      SubscriptionHistoryReasonEnum = "seller_request"
	SubscriptionHistoryReasonEnumCustomerRequest    SubscriptionHistoryReasonEnum = "customer_request"
	SubscriptionHistoryReasonEnumChargeback         SubscriptionHistoryReasonEnum = "chargeback"
	SubscriptionHistoryReasonEnumEuWithdrawal       SubscriptionHistoryReasonEnum = "eu_withdrawal"
)

// SubscriptionHistoryDiscountType: The type of discount.
type SubscriptionHistoryDiscountType string

const (
	SubscriptionHistoryDiscountTypeRecurring SubscriptionHistoryDiscountType = "recurring"
	SubscriptionHistoryDiscountTypeOneOff    SubscriptionHistoryDiscountType = "one-off"
)

// SubscriptionHistoryDiscount: Details of a discount on a subscription at the time of a history entry.
type SubscriptionHistoryDiscount struct {
	// Discount: Discount on the subscription.
	Discount Discount `json:"discount,omitempty"`
	// Type: The type of discount.
	Type SubscriptionHistoryDiscountType `json:"type,omitempty"`
	// StartsAt: RFC 3339 datetime string of when the discount is effective from on the subscription.
	StartsAt string `json:"starts_at,omitempty"`
	// EndsAt: RFC 3339 datetime string of when the discount stops being effective on the subscription. `null` if the discount does not have an end date.
	EndsAt *string `json:"ends_at,omitempty"`
}

// SubscriptionHistoryDetailItem: Represents a change to an item on the subscription at the time of a history entry.
type SubscriptionHistoryDetailItem struct {
	// Price: Price on the subscription.
	Price Price `json:"price,omitempty"`
	// Quantity: Quantity of the item on the subscription at the time of the history entry.
	Quantity int `json:"quantity,omitempty"`
}

// SubscriptionHistoryItemUpdateSummary: Summary of a quantitative change to an item on a subscription, including the direction and magnitude of the change.
type SubscriptionHistoryItemUpdateSummary struct {
	// QuantityDelta: Signed change in quantity. Positive when the quantity increased (or an item was added), negative when the quantity decreased (or an item was removed).
	QuantityDelta int `json:"quantity_delta,omitempty"`
}

// SubscriptionHistoryDetail is the dynamically-typed value of SubscriptionHistory's Detail field: a
// concrete variant pointer selected by the wire `action`, a map[string]any
// preserving the raw data for values this SDK doesn't know, or nil when the
// field is null or absent.
type SubscriptionHistoryDetail interface{}

// SubscriptionHistoryDetailSubscriptionActivated: Details specific to `subscription_activated` actions.
type SubscriptionHistoryDetailSubscriptionActivated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Status: Status of the subscription after activation.
	Status SubscriptionStatus `json:"status,omitempty"`
	// FirstBilledAt: RFC 3339 datetime string of when the subscription was first billed. `null` when the subscription has never been billed — for example, an imported subscription recovering from `past_due`.
	FirstBilledAt *string `json:"first_billed_at,omitempty"`
	// NextBilledAt: RFC 3339 datetime string of when the subscription was next scheduled to be billed at the time of activation. `null` when the subscription has no next billing date — for example, a recovered `past_due` subscription that is scheduled to cancel or pause.
	NextBilledAt *string `json:"next_billed_at,omitempty"`
	// CurrentBillingPeriod: Billing period of the subscription at the time of activation.
	CurrentBillingPeriod TimePeriod `json:"current_billing_period,omitempty"`
	// TransactionID: Paddle ID of the transaction that activated the subscription, prefixed with `txn_`.
	TransactionID string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionAddressUpdated: Details specific to `subscription_address_updated` actions.
type SubscriptionHistoryDetailSubscriptionAddressUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Address: Updated address against the subscription. This is what the address was changed to.
	Address Address `json:"address,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBillingCycleUpdated: Details specific to `subscription_billing_cycle_updated` actions.
type SubscriptionHistoryDetailSubscriptionBillingCycleUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// BillingCycle: Updated billing cycle of the subscription. This is what the billing cycle was changed to.
	BillingCycle Duration `json:"billing_cycle,omitempty"`
	// CurrentBillingPeriod: Billing period of the subscription after the billing cycle was updated.
	CurrentBillingPeriod TimePeriod `json:"current_billing_period,omitempty"`
	// NextBilledAt: RFC 3339 datetime string of when the subscription was next scheduled to be billed after the billing cycle was updated. `null` if the subscription has no next billing date (for example, paused without a scheduled resume).
	NextBilledAt *string `json:"next_billed_at,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBillingDateUpdated: Details specific to `subscription_billing_date_updated` actions.
type SubscriptionHistoryDetailSubscriptionBillingDateUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// NextBilledAt: RFC 3339 datetime string of the updated billing date. `null` when the subscription has no upcoming billing date, for example when a scheduled pause or cancellation means it will not be billed again.
	NextBilledAt *string `json:"next_billed_at,omitempty"`
	// CurrentBillingPeriod: Billing period of the subscription after the billing date was updated.
	CurrentBillingPeriod TimePeriod `json:"current_billing_period,omitempty"`
	// TransactionID: Paddle ID of the transaction created as a result of the billing date change, prefixed with `txn_`. `null` if no transaction was created.
	TransactionID *string `json:"transaction_id,omitempty"`
	// ProrationBillingMode: How proration was calculated for this billing date change.
	ProrationBillingMode ProrationBillingMode `json:"proration_billing_mode,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBillingDetailsUpdated: Details specific to `subscription_billing_details_updated` actions.
type SubscriptionHistoryDetailSubscriptionBillingDetailsUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// BillingDetails: Updated billing details on the subscription. This is what the billing details were changed to.
	BillingDetails BillingDetails `json:"billing_details,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBusinessAdded: Details specific to `subscription_business_added` actions.
type SubscriptionHistoryDetailSubscriptionBusinessAdded struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Business: New business on the subscription.
	Business Business `json:"business,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBusinessRemoved: Details specific to `subscription_business_removed` actions.
type SubscriptionHistoryDetailSubscriptionBusinessRemoved struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Business: Business that was removed from the subscription.
	Business Business `json:"business,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionBusinessUpdated: Details specific to `subscription_business_updated` actions.
type SubscriptionHistoryDetailSubscriptionBusinessUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Business: Updated business on the subscription. This is what the business was changed to.
	Business Business `json:"business,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCanceled: Details specific to `subscription_canceled` actions.
type SubscriptionHistoryDetailSubscriptionCanceled struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// EffectiveFrom: Whether the subscription was canceled immediately, or scheduled to cancel.
	EffectiveFrom *SubscriptionHistoryCanceledEffectiveFrom `json:"effective_from,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCollectionModeUpdated: Details specific to `subscription_collection_mode_updated` actions.
type SubscriptionHistoryDetailSubscriptionCollectionModeUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// CollectionMode: How payment is collected for this subscription. This is what the collection mode was changed to.
	CollectionMode CollectionMode `json:"collection_mode,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionConsentRequirementGranted: Details specific to `subscription_consent_requirement_granted` actions.
type SubscriptionHistoryDetailSubscriptionConsentRequirementGranted struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// ConsentRequirement: Details about the consent requirement that was granted.
	ConsentRequirement SubscriptionConsentRequirement `json:"consent_requirement,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCreated: Details specific to `subscription_created` actions.
type SubscriptionHistoryDetailSubscriptionCreated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Status: Status of the subscription when it was created. `null` if created before history recording began and this couldn't be determined.
	Status *SubscriptionStatus `json:"status,omitempty"`
	// CollectionMode: The collection mode of the subscription when it was created.
	CollectionMode *CollectionMode `json:"collection_mode,omitempty"`
	// BillingDetails: Details for invoicing. Only returned for manually-collected subscriptions (`collection_mode: manual`).
	BillingDetails *BillingDetails `json:"billing_details,omitempty"`
	// Customer: Customer for the subscription when it was created.
	Customer *Customer `json:"customer,omitempty"`
	// Address: Address for the subscription when it was created.
	Address *Address `json:"address,omitempty"`
	// Business: Business for the subscription when it was created.
	Business *Business `json:"business,omitempty"`
	// CurrencyCode: Supported three-letter ISO 4217 currency code of the subscription when it was created.
	CurrencyCode *CurrencyCode `json:"currency_code,omitempty"`
	// CurrentBillingPeriod: Current billing period of the subscription when it was created.
	CurrentBillingPeriod *TimePeriod `json:"current_billing_period,omitempty"`
	// BillingCycle: Billing cycle of the subscription when it was created.
	BillingCycle *Duration `json:"billing_cycle,omitempty"`
	// Items: Items on the subscription when it was created.
	Items []SubscriptionHistoryDetailItem `json:"items,omitempty"`
	// CustomData: Custom data of the subscription when it was created.
	CustomData CustomData `json:"custom_data,omitempty"`
	// Discount: Discount attached to the subscription when it was created.
	Discount *SubscriptionHistoryDiscount `json:"discount,omitempty"`
	// HasPaymentMethod: Whether the subscription had a payment method when it was created. `null` if this couldn't be determined.
	HasPaymentMethod *bool `json:"has_payment_method,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCurrencyUpdated: Details specific to `subscription_currency_updated` actions.
type SubscriptionHistoryDetailSubscriptionCurrencyUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// CurrencyCode: Updated three-letter ISO 4217 currency code for the currency on this subscription. This is what the currency was changed to.
	CurrencyCode CurrencyCode `json:"currency_code,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCustomDataUpdated: Details specific to `subscription_custom_data_updated` actions.
type SubscriptionHistoryDetailSubscriptionCustomDataUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// CustomData: Updated custom data on the subscription. `null` if custom data was removed. This is what the custom data was changed to.
	CustomData CustomData `json:"custom_data,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionCustomerUpdated: Details specific to `subscription_customer_updated` actions.
type SubscriptionHistoryDetailSubscriptionCustomerUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Customer: Updated customer on the subscription. This is what the customer was changed to.
	Customer Customer `json:"customer,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionDiscountAdded: Details specific to `subscription_discount_added` actions.
type SubscriptionHistoryDetailSubscriptionDiscountAdded struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Discount: Discount added to the subscription.
	Discount SubscriptionHistoryDiscount `json:"discount,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionDiscountExpired: Details specific to `subscription_discount_expired` actions. Recorded when a discount is no longer eligible — for example, when the maximum number of billing periods for the discount has been reached.
type SubscriptionHistoryDetailSubscriptionDiscountExpired struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Discount: Discount that expired on the subscription. `ends_at` reflects when the discount stopped being effective on the subscription. This is the discount that was removed.
	Discount SubscriptionHistoryDiscount `json:"discount,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionDiscountRemoved: Details specific to `subscription_discount_removed` actions.
type SubscriptionHistoryDetailSubscriptionDiscountRemoved struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Discount: Discount removed from the subscription.
	Discount SubscriptionHistoryDiscount `json:"discount,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionItemAdded: Details specific to `subscription_item_added` actions.
type SubscriptionHistoryDetailSubscriptionItemAdded struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Price: Price of the item that was added to the subscription.
	Price Price `json:"price,omitempty"`
	// Quantity: Quantity of the item on the subscription after being added.
	Quantity int `json:"quantity,omitempty"`
	// UpdateSummary: Summary of the quantity change. For a new item, `quantity_delta` matches the resulting `quantity` since the previous quantity was zero.
	UpdateSummary SubscriptionHistoryItemUpdateSummary `json:"update_summary,omitempty"`
	// ProrationBillingMode: How Paddle calculated proration for the item added.
	ProrationBillingMode ProrationBillingMode `json:"proration_billing_mode,omitempty"`
	// OnPaymentFailure: How Paddle handled payment failure for the operation.
	OnPaymentFailure SubscriptionOnPaymentFailure `json:"on_payment_failure,omitempty"`
	// TransactionID: Paddle ID of the transaction created as a result of the item being added, prefixed with `txn_`. `null` if no transaction was created.
	TransactionID *string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionItemQuantityUpdated: Details specific to `subscription_item_quantity_updated` actions.
type SubscriptionHistoryDetailSubscriptionItemQuantityUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Price: Price of the item where the quantity was updated.
	Price Price `json:"price,omitempty"`
	// Quantity: Total quantity of the item on the subscription after the change.
	Quantity int `json:"quantity,omitempty"`
	// UpdateSummary: Summary of the quantity change. `quantity_delta` is positive when the quantity increased, negative when it decreased.
	UpdateSummary SubscriptionHistoryItemUpdateSummary `json:"update_summary,omitempty"`
	// ProrationBillingMode: How Paddle calculated proration for the quantity change.
	ProrationBillingMode ProrationBillingMode `json:"proration_billing_mode,omitempty"`
	// OnPaymentFailure: How Paddle handled payment failure for the operation.
	OnPaymentFailure SubscriptionOnPaymentFailure `json:"on_payment_failure,omitempty"`
	// TransactionID: Paddle ID of the transaction created as a result of the quantity change, prefixed with `txn_`. `null` if no transaction was created.
	TransactionID *string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionItemRemoved: Details specific to `subscription_item_removed` actions.
type SubscriptionHistoryDetailSubscriptionItemRemoved struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Price: Price of the item that was removed from the subscription.
	Price Price `json:"price,omitempty"`
	// Quantity: Quantity of the item on the subscription after the removal. Always `0` since the item no longer exists on the subscription.
	Quantity int `json:"quantity,omitempty"`
	// UpdateSummary: Summary of the quantity change. `quantity_delta` is negative, reflecting the amount removed.
	UpdateSummary SubscriptionHistoryItemUpdateSummary `json:"update_summary,omitempty"`
	// ProrationBillingMode: How Paddle calculated proration for the item removal.
	ProrationBillingMode ProrationBillingMode `json:"proration_billing_mode,omitempty"`
	// OnPaymentFailure: How Paddle handled payment failure for the operation.
	OnPaymentFailure SubscriptionOnPaymentFailure `json:"on_payment_failure,omitempty"`
	// TransactionID: Paddle ID of the transaction created as a result of the item being removed, prefixed with `txn_`. `null` if no transaction was created.
	TransactionID *string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionOneOffChargeApplied: Details specific to `subscription_one_off_charge_applied` actions.
type SubscriptionHistoryDetailSubscriptionOneOffChargeApplied struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// EffectiveFrom: When the customer was billed for the one-off charge.
	EffectiveFrom SubscriptionHistoryOneOffChargeAppliedEffectiveFrom `json:"effective_from,omitempty"`
	// Items: Items that were charged as part of the one-off charge.
	Items []SubscriptionHistoryDetailItem `json:"items,omitempty"`
	// OnPaymentFailure: How Paddle handled payment failure for the one-off charge.
	OnPaymentFailure SubscriptionOnPaymentFailure `json:"on_payment_failure,omitempty"`
	// TransactionID: Paddle ID of the transaction created for the one-off charge, prefixed with `txn_`. `null` if no transaction was created.
	TransactionID *string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPastDue: Details specific to `subscription_past_due` actions.
type SubscriptionHistoryDetailSubscriptionPastDue struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Status: The status of the subscription after becoming past due.
	Status SubscriptionStatus `json:"status,omitempty"`
	// TransactionID: Paddle ID of the failed transaction, prefixed with `txn_`.
	TransactionID string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPaused: Details specific to `subscription_paused` actions.
type SubscriptionHistoryDetailSubscriptionPaused struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// EffectiveFrom: Whether the subscription was paused immediately, or scheduled to pause.
	EffectiveFrom SubscriptionHistoryPausedEffectiveFrom `json:"effective_from,omitempty"`
	// Status: The status of the subscription after pausing.
	Status SubscriptionStatus `json:"status,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPaymentAttempted: Details specific to `subscription_payment_attempted` actions. Recorded when a payment attempt fails for an operation that attempts a payment, like a subscription update or one-time charge. Successful payment outcomes are captured by the relevant action, like `subscription_item_added`, `subscription_one_off_charge_applied`, or `subscription_activated`.
type SubscriptionHistoryDetailSubscriptionPaymentAttempted struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Operation: Operation that resulted in the failed payment attempt. Use the related transaction ID to get the full details of the attempted change.
	Operation SubscriptionHistoryPaymentAttemptedOperation `json:"operation,omitempty"`
	// TransactionID: Paddle ID of the failed transaction, prefixed with `txn_`.
	TransactionID string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPaymentMethodAdded: Details specific to `subscription_payment_method_added` actions.
type SubscriptionHistoryDetailSubscriptionPaymentMethodAdded struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPaymentMethodRemoved: Details specific to `subscription_payment_method_removed` actions.
type SubscriptionHistoryDetailSubscriptionPaymentMethodRemoved struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionPaymentMethodUpdated: Details specific to `subscription_payment_method_updated` actions.
type SubscriptionHistoryDetailSubscriptionPaymentMethodUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionRenewed: Details specific to `subscription_renewed` actions.
type SubscriptionHistoryDetailSubscriptionRenewed struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// NextBilledAt: RFC 3339 datetime string of when the subscription was next scheduled to be billed after this renewal.
	NextBilledAt string `json:"next_billed_at,omitempty"`
	// CurrentBillingPeriod: Billing period of the subscription after renewal.
	CurrentBillingPeriod TimePeriod `json:"current_billing_period,omitempty"`
	// TransactionID: Paddle ID of the transaction created for this renewal, prefixed with `txn_`.
	TransactionID string `json:"transaction_id,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionResumed: Details specific to `subscription_resumed` actions.
type SubscriptionHistoryDetailSubscriptionResumed struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// Status: The status of the subscription after resuming.
	Status SubscriptionStatus `json:"status,omitempty"`
	// OnResume: How the subscription was resumed. Indicates whether a new billing period was started or the existing one continued.
	OnResume SubscriptionOnResume `json:"on_resume,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionScheduledChangeAdded: Details specific to `subscription_scheduled_change_added` actions.
type SubscriptionHistoryDetailSubscriptionScheduledChangeAdded struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// ScheduledChange: Details of the scheduled change that was added to the subscription.
	ScheduledChange SubscriptionScheduledChange `json:"scheduled_change,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionScheduledChangeRemoved: Details specific to `subscription_scheduled_change_removed` actions.
type SubscriptionHistoryDetailSubscriptionScheduledChangeRemoved struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// ScheduledChange: Details of the scheduled change that was removed from the subscription.
	ScheduledChange SubscriptionScheduledChange `json:"scheduled_change,omitempty"`
}

// SubscriptionHistoryDetailSubscriptionScheduledChangeUpdated: Details specific to `subscription_scheduled_change_updated` actions.
type SubscriptionHistoryDetailSubscriptionScheduledChangeUpdated struct {
	// Action: What happened on the subscription.
	Action string `json:"action,omitempty"`
	// ScheduledChange: Details of the updated scheduled change on the subscription. This is what the scheduled change was changed to.
	ScheduledChange SubscriptionScheduledChange `json:"scheduled_change,omitempty"`
}

// SubscriptionHistory: Represents a subscription history entry.
type SubscriptionHistory struct {
	// ID: Unique Paddle ID for this subscription history entry, prefixed with `subhis_`.
	ID string `json:"id,omitempty"`
	// GroupID: Unique Paddle ID for this subscription history group, prefixed with `subhisgrp_`. History entries that occurred as part of the same request share the same group ID.
	GroupID string `json:"group_id,omitempty"`
	// SubscriptionID: Paddle ID of the subscription that this history entry relates to, prefixed with `sub_`.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// OccurredAt: RFC 3339 datetime string of when the entry happened.
	OccurredAt string `json:"occurred_at,omitempty"`
	// Source: Where the entry originated from.
	Source ActionSource `json:"source,omitempty"`
	// Actor: Details about the actor that performed the action that created this entry.
	Actor Actor `json:"actor,omitempty"`
	// Reason: Why the entry was created. Only applicable to certain actions; `null` otherwise.
	Reason *SubscriptionHistoryReasonEnum `json:"reason,omitempty"`
	// Detail: Details specific to the action. The fields returned depend on the value of `action`.
	Detail SubscriptionHistoryDetail `json:"detail,omitempty"`
}

// UnmarshalJSON implements the json.Unmarshaler interface for SubscriptionHistory,
// hydrating Detail into the concrete variant selected by the wire `action`.
func (s *SubscriptionHistory) UnmarshalJSON(data []byte) error {
	type alias SubscriptionHistory
	aux := struct {
		*alias
		Detail json.RawMessage `json:"detail"`
	}{alias: (*alias)(s)}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	if len(aux.Detail) == 0 || string(aux.Detail) == "null" {
		s.Detail = nil
		return nil
	}

	var disc struct {
		Action string `json:"action"`
	}
	if err := json.Unmarshal(aux.Detail, &disc); err != nil {
		return err
	}

	var t SubscriptionHistoryDetail
	switch disc.Action {
	case "subscription_activated":
		t = &SubscriptionHistoryDetailSubscriptionActivated{}
	case "subscription_address_updated":
		t = &SubscriptionHistoryDetailSubscriptionAddressUpdated{}
	case "subscription_billing_cycle_updated":
		t = &SubscriptionHistoryDetailSubscriptionBillingCycleUpdated{}
	case "subscription_billing_date_updated":
		t = &SubscriptionHistoryDetailSubscriptionBillingDateUpdated{}
	case "subscription_billing_details_updated":
		t = &SubscriptionHistoryDetailSubscriptionBillingDetailsUpdated{}
	case "subscription_business_added":
		t = &SubscriptionHistoryDetailSubscriptionBusinessAdded{}
	case "subscription_business_removed":
		t = &SubscriptionHistoryDetailSubscriptionBusinessRemoved{}
	case "subscription_business_updated":
		t = &SubscriptionHistoryDetailSubscriptionBusinessUpdated{}
	case "subscription_canceled":
		t = &SubscriptionHistoryDetailSubscriptionCanceled{}
	case "subscription_collection_mode_updated":
		t = &SubscriptionHistoryDetailSubscriptionCollectionModeUpdated{}
	case "subscription_consent_requirement_granted":
		t = &SubscriptionHistoryDetailSubscriptionConsentRequirementGranted{}
	case "subscription_created":
		t = &SubscriptionHistoryDetailSubscriptionCreated{}
	case "subscription_currency_updated":
		t = &SubscriptionHistoryDetailSubscriptionCurrencyUpdated{}
	case "subscription_custom_data_updated":
		t = &SubscriptionHistoryDetailSubscriptionCustomDataUpdated{}
	case "subscription_customer_updated":
		t = &SubscriptionHistoryDetailSubscriptionCustomerUpdated{}
	case "subscription_discount_added":
		t = &SubscriptionHistoryDetailSubscriptionDiscountAdded{}
	case "subscription_discount_expired":
		t = &SubscriptionHistoryDetailSubscriptionDiscountExpired{}
	case "subscription_discount_removed":
		t = &SubscriptionHistoryDetailSubscriptionDiscountRemoved{}
	case "subscription_item_added":
		t = &SubscriptionHistoryDetailSubscriptionItemAdded{}
	case "subscription_item_quantity_updated":
		t = &SubscriptionHistoryDetailSubscriptionItemQuantityUpdated{}
	case "subscription_item_removed":
		t = &SubscriptionHistoryDetailSubscriptionItemRemoved{}
	case "subscription_one_off_charge_applied":
		t = &SubscriptionHistoryDetailSubscriptionOneOffChargeApplied{}
	case "subscription_past_due":
		t = &SubscriptionHistoryDetailSubscriptionPastDue{}
	case "subscription_paused":
		t = &SubscriptionHistoryDetailSubscriptionPaused{}
	case "subscription_payment_attempted":
		t = &SubscriptionHistoryDetailSubscriptionPaymentAttempted{}
	case "subscription_payment_method_added":
		t = &SubscriptionHistoryDetailSubscriptionPaymentMethodAdded{}
	case "subscription_payment_method_removed":
		t = &SubscriptionHistoryDetailSubscriptionPaymentMethodRemoved{}
	case "subscription_payment_method_updated":
		t = &SubscriptionHistoryDetailSubscriptionPaymentMethodUpdated{}
	case "subscription_renewed":
		t = &SubscriptionHistoryDetailSubscriptionRenewed{}
	case "subscription_resumed":
		t = &SubscriptionHistoryDetailSubscriptionResumed{}
	case "subscription_scheduled_change_added":
		t = &SubscriptionHistoryDetailSubscriptionScheduledChangeAdded{}
	case "subscription_scheduled_change_removed":
		t = &SubscriptionHistoryDetailSubscriptionScheduledChangeRemoved{}
	case "subscription_scheduled_change_updated":
		t = &SubscriptionHistoryDetailSubscriptionScheduledChangeUpdated{}
	default:
		raw := map[string]any{}
		if err := json.Unmarshal(aux.Detail, &raw); err != nil {
			return err
		}
		s.Detail = raw
		return nil
	}

	if err := json.Unmarshal(aux.Detail, t); err != nil {
		return err
	}

	s.Detail = t

	return nil
}

// SubscriptionHistoriesClient is a client for the Subscription history resource.
type SubscriptionHistoriesClient struct {
	doer Doer
}

// ListSubscriptionHistoryRequest is given as an input to ListSubscriptionHistory.
type ListSubscriptionHistoryRequest struct {
	// URL path parameters.
	SubscriptionID string `in:"path=subscription_id" json:"-"`

	// Action is a query parameter.
	// Return history entries that match the specified action. Use a comma-separated list to specify multiple action values.
	Action []string `in:"query=action;omitempty" json:"-"`
	// Source is a query parameter.
	// Return history entries that match the specified source. Use a comma-separated list to specify multiple source values.
	Source []string `in:"query=source;omitempty" json:"-"`
	// ActorType is a query parameter.
	// Return history entries that match the specified actor type. Use a comma-separated list to specify multiple actor type values.
	ActorType []string `in:"query=actor_type;omitempty" json:"-"`
	// ActorID is a query parameter.
	// Return history entries that match the specified actor ID. Use a comma-separated list to specify multiple actor ID values. Only applicable if `actor_type` is also selected.
	ActorID []string `in:"query=actor_id;omitempty" json:"-"`
	// Reason is a query parameter.
	// Return history entries that match the specified reason. Use a comma-separated list to specify multiple reason values.
	Reason []string `in:"query=reason;omitempty" json:"-"`
	// OccurredAt is a query parameter.
	// Return entities that occurred at a specific time. Use `[LTE]` (less than or equal to) or `[GTE]` (greater than or equal to) operators with an RFC 3339 datetime string. For example, `occurred_at[LTE]=2023-04-18T17:03:26` or `occurred_at[GTE]=2023-04-18T17:03:26`.
	OccurredAt *string `in:"query=occurred_at;omitempty" json:"-"`
	// After is a query parameter.
	// Return entities after the specified Paddle ID when working with paginated endpoints. Used in the `meta.pagination.next` URL in responses for list operations.
	After *string `in:"query=after;omitempty" json:"-"`
	// PerPage is a query parameter.
	/*
	   Set how many entities are returned per page. Paddle returns the maximum number of results if a number greater than the maximum is requested. Check `meta.pagination.per_page` in the response to see how many were returned.

	   Default: `50`; Maximum: `200`.
	*/
	PerPage *int `in:"query=per_page;omitempty" json:"-"`
	// OrderBy is a query parameter.
	/*
	   Order returned entities by the specified field and direction (`[ASC]` or `[DESC]`). For example, `?order_by=id[DESC]`.

	   Valid fields for ordering: `id`.
	*/
	OrderBy *string `in:"query=order_by;omitempty" json:"-"`
}

// ListSubscriptionHistory performs the GET operation on a Subscription history resource.
func (c *SubscriptionHistoriesClient) ListSubscriptionHistory(ctx context.Context, req *ListSubscriptionHistoryRequest) (res *Collection[*SubscriptionHistory], err error) {
	if err := c.doer.Do(ctx, "GET", "/subscriptions/{subscription_id}/history", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
