// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddle

import "context"

// VerificationStatus: Overall status of the verification, derived from the status of its steps.
type VerificationStatus string

const (
	VerificationStatusPending        VerificationStatus = "pending"
	VerificationStatusInProgress     VerificationStatus = "in_progress"
	VerificationStatusInReview       VerificationStatus = "in_review"
	VerificationStatusActionRequired VerificationStatus = "action_required"
	VerificationStatusCompleted      VerificationStatus = "completed"
	VerificationStatusFailed         VerificationStatus = "failed"
)

// VerificationType: Type of verification.
type VerificationType string

const (
	VerificationTypeOnboarding VerificationType = "onboarding"
	VerificationTypeDomain     VerificationType = "domain"
)

// VerificationStepKey: Key of the verification step.
type VerificationStepKey string

const (
	VerificationStepKeyAccountSetup           VerificationStepKey = "account_setup"
	VerificationStepKeyDomainReview           VerificationStepKey = "domain_review"
	VerificationStepKeyBusinessIdentification VerificationStepKey = "business_identification"
	VerificationStepKeyIdentityVerification   VerificationStepKey = "identity_verification"
	VerificationStepKeyFinalReview            VerificationStepKey = "final_review"
	VerificationStepKeyAutomatedReview        VerificationStepKey = "automated_review"
)

/*
VerificationStepStatus: Status of the verification step.

Steps are created as `pending` initially, then move through `in_progress` and `in_review` states as Paddle processes each step.
*/
type VerificationStepStatus string

const (
	VerificationStepStatusPending        VerificationStepStatus = "pending"
	VerificationStepStatusInProgress     VerificationStepStatus = "in_progress"
	VerificationStepStatusInReview       VerificationStepStatus = "in_review"
	VerificationStepStatusActionRequired VerificationStepStatus = "action_required"
	VerificationStepStatusFailed         VerificationStepStatus = "failed"
	VerificationStepStatusCompleted      VerificationStepStatus = "completed"
)

// VerificationStep: Represents a verification step entity.
type VerificationStep struct {
	ID  string              `json:"id,omitempty"`
	Key VerificationStepKey `json:"key,omitempty"`
	// Status: Status of the verification step.
	Status VerificationStepStatus `json:"status,omitempty"`
	// ExpiresAt: RFC 3339 datetime string of when this step expires. `null` if this step never expires.
	ExpiresAt *string `json:"expires_at,omitempty"`
	CreatedAt string  `json:"created_at,omitempty"`
	UpdatedAt string  `json:"updated_at,omitempty"`
}

// Verification: Represents a verification entity.
type Verification struct {
	ID string `json:"id,omitempty"`
	// Status: Overall status of the verification, derived from the status of its steps. `pending` until the first step exists.
	Status VerificationStatus `json:"status,omitempty"`
	// VerificationType: Type of verification. An account has at most one `onboarding` verification.
	VerificationType VerificationType `json:"verification_type,omitempty"`
	CreatedAt        string           `json:"created_at,omitempty"`
	UpdatedAt        string           `json:"updated_at,omitempty"`
	// Steps: Verification steps that make up this verification.
	Steps []VerificationStep `json:"steps,omitempty"`
}

// VerificationsClient is a client for the Verifications resource.
type VerificationsClient struct {
	doer Doer
}

// ListVerificationsRequest is given as an input to ListVerifications.
type ListVerificationsRequest struct {
	// ID is a query parameter.
	// Return only the IDs specified. Use a comma-separated list to get multiple entities.
	ID []string `in:"query=id;omitempty" json:"-"`
	// After is a query parameter.
	// Return entities after the specified Paddle ID when working with paginated endpoints. Used in the `meta.pagination.next` URL in responses for list operations.
	After *string `in:"query=after;omitempty" json:"-"`
	// PerPage is a query parameter.
	/*
	   Set how many entities are returned per page. Paddle returns the maximum number of results if a number greater than the maximum is requested. Check `meta.pagination.per_page` in the response to see how many were returned.

	   Default: `50`; Maximum: `200`.
	*/
	PerPage *int `in:"query=per_page;omitempty" json:"-"`
	// VerificationType is a query parameter.
	// Filter verifications by type. If omitted, verifications of all types are returned.
	VerificationType *string `in:"query=verification_type;omitempty" json:"-"`
	// OrderBy is a query parameter.
	/*
	   Order returned entities by the specified field and direction (`[ASC]` or `[DESC]`). For example, `?order_by=id[ASC]`.

	   Valid fields for ordering: `id`.
	*/
	OrderBy *string `in:"query=order_by;omitempty" json:"-"`
}

// ListVerifications performs the GET operation on a Verifications resource.
func (c *VerificationsClient) ListVerifications(ctx context.Context, req *ListVerificationsRequest) (res *Collection[*Verification], err error) {
	if err := c.doer.Do(ctx, "GET", "/verifications", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}

// GetVerificationRequest is given as an input to GetVerification.
type GetVerificationRequest struct {
	// URL path parameters.
	VerificationID string `in:"path=verification_id" json:"-"`
}

// GetVerification performs the GET operation on a Verifications resource.
func (c *VerificationsClient) GetVerification(ctx context.Context, req *GetVerificationRequest) (res *Verification, err error) {
	if err := c.doer.Do(ctx, "GET", "/verifications/{verification_id}", req, &res); err != nil {
		return nil, err
	}

	return res, nil
}
