// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// AdjustmentCreated represents a adjustment webhook notification entity.
// See https://developer.paddle.com/webhooks/overview for more information.
type AdjustmentCreated struct {
	GenericNotificationsEvent
	Data AdjustmentNotification `json:"data"`
}

// AdjustmentUpdated represents a adjustment webhook notification entity.
// See https://developer.paddle.com/webhooks/overview for more information.
type AdjustmentUpdated struct {
	GenericNotificationsEvent
	Data AdjustmentNotification `json:"data"`
}

// AdjustmentNotification: New or changed entity.
type AdjustmentNotification struct {
	// ID: Unique Paddle ID for this adjustment entity, prefixed with `adj_`.
	ID string `json:"id,omitempty"`
	// Action: How this adjustment impacts the related transaction. `refund` adjustments must be approved by Paddle, and are created with the status `pending_approval`.
	Action string `json:"action,omitempty"`
	// TransactionID: Paddle ID for the transaction related to this adjustment, prefixed with `txn_`.
	TransactionID string `json:"transaction_id,omitempty"`
	/*
	   SubscriptionID: Paddle ID for the subscription related to this adjustment, prefixed with `sub_`.
	   Set automatically by Paddle based on the `subscription_id` of the related transaction.
	*/
	SubscriptionID *string `json:"subscription_id,omitempty"`
	/*
	   CustomerID: Paddle ID for the customer related to this adjustment, prefixed with `ctm_`.
	   Set automatically by Paddle based on the `customer_id` of the related transaction.
	*/
	CustomerID string `json:"customer_id,omitempty"`
	// Reason: Why this adjustment was created. Appears in the Paddle Dashboard. Retained for record-keeping purposes.
	Reason string `json:"reason,omitempty"`
	/*
	   CreditAppliedToBalance: Whether this adjustment was applied to the related customer's credit balance. Only returned for `credit` adjustments.

	   `false` when the related transaction `collection_mode` is `manual` and its `status` is `billed`. The adjustment is used
	   to reduce the `balance` due on the transaction.

	   `true` for automatically-collected transactions and `completed` manually-collected transactions.
	*/
	CreditAppliedToBalance *bool `json:"credit_applied_to_balance,omitempty"`
	// CurrencyCode: Three-letter ISO 4217 currency code for this adjustment. Set automatically by Paddle based on the `currency_code` of the related transaction.
	CurrencyCode string `json:"currency_code,omitempty"`
	/*
	   Status: Status of this adjustment. Set automatically by Paddle.

	   `refund` adjustments must be approved by Paddle, and are created with the status `pending_approval`
	   until they move to `approved` or `rejected` on review. Other kinds of adjustment do not need approval,
	   so are created with the status `approved`.
	*/
	Status string `json:"status,omitempty"`
	// Items: List of items on this adjustment.
	Items []AdjustmentItem `json:"items,omitempty"`
	// Totals: Breakdown of the total for an adjustment.
	Totals AdjustmentTotals `json:"totals,omitempty"`
	// PayoutTotals: Breakdown of how this adjustment affects your payout balance.
	PayoutTotals *PayoutTotalsAdjustment `json:"payout_totals,omitempty"`
	// CreatedAt: RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
	UpdatedAt string `json:"updated_at,omitempty"`
}
