// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// APIKeyCreated represents the api_key.created event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyCreated struct {
	GenericNotificationEvent
	Data APIKeyNotification `json:"data"`
}

// APIKeyUpdated represents the api_key.updated event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyUpdated struct {
	GenericNotificationEvent
	Data APIKeyNotification `json:"data"`
}

// APIKeyExpired represents the api_key.expired event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyExpired struct {
	GenericNotificationEvent
	Data APIKeyNotification `json:"data"`
}

// APIKeyExpiring represents the api_key.expiring event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyExpiring struct {
	GenericNotificationEvent
	Data APIKeyNotification `json:"data"`
}

// APIKeyRevoked represents the api_key.revoked event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyRevoked struct {
	GenericNotificationEvent
	Data APIKeyNotification `json:"data"`
}

// APIKeyExposureCreated represents the api_key_exposure.created event.
// See https://developer.paddle.com/webhooks/overview for more information.
type APIKeyExposureCreated struct {
	GenericNotificationEvent
	Data APIKeyExposureNotification `json:"data"`
}

// APIKeyStatus: Status of this API key..
type APIKeyStatus string

const (
	APIKeyStatusActive  APIKeyStatus = "active"
	APIKeyStatusExpired APIKeyStatus = "expired"
	APIKeyStatusRevoked APIKeyStatus = "revoked"
)

// APIKeyPermission: Permission assigned to this API key..
type APIKeyPermission string

const (
	APIKeyPermissionAddressRead                 APIKeyPermission = "address.read"
	APIKeyPermissionAddressWrite                APIKeyPermission = "address.write"
	APIKeyPermissionAdjustmentRead              APIKeyPermission = "adjustment.read"
	APIKeyPermissionAdjustmentWrite             APIKeyPermission = "adjustment.write"
	APIKeyPermissionBusinessRead                APIKeyPermission = "business.read"
	APIKeyPermissionBusinessWrite               APIKeyPermission = "business.write"
	APIKeyPermissionClientTokenRead             APIKeyPermission = "client_token.read"
	APIKeyPermissionClientTokenWrite            APIKeyPermission = "client_token.write"
	APIKeyPermissionCustomerRead                APIKeyPermission = "customer.read"
	APIKeyPermissionCustomerWrite               APIKeyPermission = "customer.write"
	APIKeyPermissionCustomerAuthTokenWrite      APIKeyPermission = "customer_auth_token.write"
	APIKeyPermissionCustomerPortalSessionWrite  APIKeyPermission = "customer_portal_session.write"
	APIKeyPermissionDiscountRead                APIKeyPermission = "discount.read"
	APIKeyPermissionDiscountWrite               APIKeyPermission = "discount.write"
	APIKeyPermissionNotificationRead            APIKeyPermission = "notification.read"
	APIKeyPermissionNotificationWrite           APIKeyPermission = "notification.write"
	APIKeyPermissionNotificationSettingRead     APIKeyPermission = "notification_setting.read"
	APIKeyPermissionNotificationSettingWrite    APIKeyPermission = "notification_setting.write"
	APIKeyPermissionNotificationSimulationRead  APIKeyPermission = "notification_simulation.read"
	APIKeyPermissionNotificationSimulationWrite APIKeyPermission = "notification_simulation.write"
	APIKeyPermissionPaymentMethodRead           APIKeyPermission = "payment_method.read"
	APIKeyPermissionPaymentMethodWrite          APIKeyPermission = "payment_method.write"
	APIKeyPermissionPriceRead                   APIKeyPermission = "price.read"
	APIKeyPermissionPriceWrite                  APIKeyPermission = "price.write"
	APIKeyPermissionProductRead                 APIKeyPermission = "product.read"
	APIKeyPermissionProductWrite                APIKeyPermission = "product.write"
	APIKeyPermissionReportRead                  APIKeyPermission = "report.read"
	APIKeyPermissionReportWrite                 APIKeyPermission = "report.write"
	APIKeyPermissionSubscriptionRead            APIKeyPermission = "subscription.read"
	APIKeyPermissionSubscriptionWrite           APIKeyPermission = "subscription.write"
	APIKeyPermissionTransactionRead             APIKeyPermission = "transaction.read"
	APIKeyPermissionTransactionWrite            APIKeyPermission = "transaction.write"
)

// APIKeyNotification: New or changed entity.
type APIKeyNotification struct {
	NotificationPayload `json:"-"`

	// ID: Unique Paddle ID for this API key entity, prefixed with `apikey_`.
	ID string `json:"id"`
	// Name: Short name of this API key. Typically unique and human-identifiable.
	Name string `json:"name"`
	// Description: Short description of this API key. Typically gives details about what the API key is used for and where it's used.
	Description *string `json:"description"`
	// Key: An obfuscated version of this API key, prefixed with `pdl_` and containing `_apikey_ `.
	Key string `json:"key"`
	// Status: Status of this API key.
	Status APIKeyStatus `json:"status"`
	// Permissions: Permission assigned to this API key.
	Permissions []APIKeyPermission `json:"permissions"`
	// ExposedAt: RFC 3339 datetime string of when this API key was first exposed. `null` if never exposed.
	ExposedAt *string `json:"exposed_at"`
	// ExpiresAt: RFC 3339 datetime string of when this API key expires.
	ExpiresAt *string `json:"expires_at"`
	// LastUsedAt: RFC 3339 datetime string of when this API key was last used (accurate to within 1 hour). `null` if never used.
	LastUsedAt *string `json:"last_used_at"`
	// CreatedAt: RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.
	CreatedAt string `json:"created_at"`
	// UpdatedAt: RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
	UpdatedAt string `json:"updated_at"`
}

// APIKeyExposureLevel: Risk level of this exposure..
type APIKeyExposureLevel string

const (
	APIKeyExposureLevelHigh APIKeyExposureLevel = "high"
	APIKeyExposureLevelLow  APIKeyExposureLevel = "low"
)

// APIKeyExposureActionTaken: Action performed by Paddle as a result of this exposure..
type APIKeyExposureActionTaken string

const (
	APIKeyExposureActionTakenRevoked APIKeyExposureActionTaken = "revoked"
	APIKeyExposureActionTakenNone    APIKeyExposureActionTaken = "none"
)

// APIKeyExposureSource: Source of this exposure..
type APIKeyExposureSource string

const APIKeyExposureSourceGithub APIKeyExposureSource = "github"

// APIKeyExposureNotification: New or changed entity.
type APIKeyExposureNotification struct {
	NotificationPayload `json:"-"`

	// ID: Unique Paddle ID for this API key exposure entity, prefixed with `apkexp_`.
	ID string `json:"id"`
	// APIKeyID: Unique Paddle ID for this API key entity, prefixed with `apikey_`.
	APIKeyID string `json:"api_key_id"`
	// RiskLevel: Risk level of this exposure.
	RiskLevel APIKeyExposureLevel `json:"risk_level"`
	// ActionTaken: Action performed by Paddle as a result of this exposure.
	ActionTaken APIKeyExposureActionTaken `json:"action_taken"`
	// Source: Source of this exposure.
	Source APIKeyExposureSource `json:"source"`
	// Reference: A unique URL or reference pointing to the source of the exposure. When `source` is `github`, a URL to the location of the exposure is returned.
	Reference string `json:"reference"`
	// Description: Additional details about this exposure.
	Description *string `json:"description"`
	// CreatedAt: RFC 3339 datetime string of when this API key exposure was found. Set automatically by Paddle.
	CreatedAt string `json:"created_at"`
}
