// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// BusinessCreated represents the business.created event.
// See https://developer.paddle.com/webhooks/overview for more information.
type BusinessCreated struct {
	GenericNotificationEvent
	Data BusinessNotification `json:"data"`
}

// BusinessImported represents the business.imported event.
// See https://developer.paddle.com/webhooks/overview for more information.
type BusinessImported struct {
	GenericNotificationEvent
	Data BusinessNotification `json:"data"`
}

// BusinessUpdated represents the business.updated event.
// See https://developer.paddle.com/webhooks/overview for more information.
type BusinessUpdated struct {
	GenericNotificationEvent
	Data BusinessNotification `json:"data"`
}

// Contacts: List of contacts related to this business, typically used for sending invoices.
type Contacts struct {
	// Name: Full name of this contact.
	Name string `json:"name,omitempty"`
	// Email: Email address for this contact.
	Email string `json:"email,omitempty"`
}

// BusinessNotification: New or changed entity.
type BusinessNotification struct {
	NotificationPayload `json:"-"`

	// ID: Unique Paddle ID for this business entity, prefixed with `biz_`.
	ID string `json:"id"`
	// CustomerID: Paddle ID for the customer related to this business, prefixed with `cus_`.
	CustomerID string `json:"customer_id"`
	// Name: Name of this business.
	Name string `json:"name"`
	// CompanyNumber: Company number for this business.
	CompanyNumber *string `json:"company_number"`
	// TaxIdentifier: Tax or VAT Number for this business.
	TaxIdentifier *string `json:"tax_identifier"`
	// Status: Whether this entity can be used in Paddle.
	Status Status `json:"status"`
	// Contacts: List of contacts related to this business, typically used for sending invoices.
	Contacts []Contacts `json:"contacts"`
	// CreatedAt: RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.
	CreatedAt string `json:"created_at"`
	// UpdatedAt: RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
	UpdatedAt string `json:"updated_at"`
	// CustomData: Your own structured key-value data.
	CustomData CustomData `json:"custom_data"`
	// ImportMeta: Import information for this entity. `null` if this entity is not imported.
	ImportMeta *ImportMeta `json:"import_meta"`
}
