// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

type NotificationsEvent interface{}

// GenericNotificationsEvent: Notification payload. Includes the new or changed event.
type GenericNotificationsEvent struct {
	NotificationsEvent

	// EventID: Unique Paddle ID for this event, prefixed with `evt_`.
	EventID string `json:"event_id,omitempty"`
	// EventType: Type of event sent by Paddle, in the format `entity.event_type`.
	EventType string `json:"event_type,omitempty"`
	// OccurredAt: RFC 3339 datetime string of when this event occurred.
	OccurredAt string `json:"occurred_at,omitempty"`
	// Data: New or changed entity.
	Data any `json:"data,omitempty"`
	// NotificationID: Unique Paddle ID for this notification, prefixed with `ntf_`.
	NotificationID string `json:"notification_id,omitempty"`
}
