// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

type NotificationEvent interface{}

type NotificationPayload interface{}

// GenericNotificationEvent: Notification payload. Includes the new or changed event.
type GenericNotificationEvent struct {
	NotificationEvent

	// EventID: Unique Paddle ID for this event, prefixed with `evt_`.
	EventID string `json:"event_id,omitempty"`
	// EventType: Type of event sent by Paddle, in the format `entity.event_type`.
	EventType EventTypeName `json:"event_type,omitempty"`
	// OccurredAt: RFC 3339 datetime string of when this event occurred.
	OccurredAt string `json:"occurred_at,omitempty"`
	// Data: New or changed entity.
	Data NotificationPayload `json:"data,omitempty"`
	// NotificationID: Unique Paddle ID for this notification, prefixed with `ntf_`.
	NotificationID string `json:"notification_id,omitempty"`
}
