// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// PaymentMethodSaved represents the payment_method.saved event.
// See https://developer.paddle.com/webhooks/overview for more information.
type PaymentMethodSaved struct {
	GenericNotificationEvent
	Data PaymentMethodSavedNotification `json:"data"`
}

// PaymentMethodDeleted represents the payment_method.deleted event.
// See https://developer.paddle.com/webhooks/overview for more information.
type PaymentMethodDeleted struct {
	GenericNotificationEvent
	Data PaymentMethodDeletedNotification `json:"data"`
}

// SavedPaymentMethodType: Type of payment method saved..
type SavedPaymentMethodType string

const (
	SavedPaymentMethodTypeAlipay    SavedPaymentMethodType = "alipay"
	SavedPaymentMethodTypeApplePay  SavedPaymentMethodType = "apple_pay"
	SavedPaymentMethodTypeCard      SavedPaymentMethodType = "card"
	SavedPaymentMethodTypeGooglePay SavedPaymentMethodType = "google_pay"
	SavedPaymentMethodTypePaypal    SavedPaymentMethodType = "paypal"
)

// Origin: Describes how this payment method was saved..
type Origin string

const (
	OriginSavedDuringPurchase Origin = "saved_during_purchase"
	OriginSubscription        Origin = "subscription"
)

// PaymentMethodSavedNotification: New or changed entity.
type PaymentMethodSavedNotification struct {
	NotificationPayload `json:"-"`

	// ID: Unique Paddle ID for this payment method entity, prefixed with `paymtd_`.
	ID string `json:"id"`
	// CustomerID: Paddle ID of the customer that this payment method is saved for, prefixed with `ctm_`.
	CustomerID string `json:"customer_id"`
	// AddressID: Paddle ID of the address for this payment method, prefixed with `add_`.
	AddressID string `json:"address_id"`
	// Type: Type of payment method saved.
	Type SavedPaymentMethodType `json:"type"`
	// Origin: Describes how this payment method was saved.
	Origin Origin `json:"origin"`
	// SavedAt: RFC 3339 datetime string of when this entity was saved. Set automatically by Paddle.
	SavedAt string `json:"saved_at"`
	// UpdatedAt: RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
	UpdatedAt string `json:"updated_at"`
}

// PaymentMethodDeletionReason: Reason why this payment method was deleted..
type PaymentMethodDeletionReason string

const (
	PaymentMethodDeletionReasonReplacedByNewerVersion PaymentMethodDeletionReason = "replaced_by_newer_version"
	PaymentMethodDeletionReasonAPI                    PaymentMethodDeletionReason = "api"
)

// PaymentMethodOrigin: Describes how this payment method was saved..
type PaymentMethodOrigin string

const (
	PaymentMethodOriginSavedDuringPurchase PaymentMethodOrigin = "saved_during_purchase"
	PaymentMethodOriginSubscription        PaymentMethodOrigin = "subscription"
)

// PaymentMethodDeletedNotification: New or changed entity.
type PaymentMethodDeletedNotification struct {
	NotificationPayload `json:"-"`

	// ID: Unique Paddle ID for this payment method entity, prefixed with `paymtd_`.
	ID string `json:"id"`
	// CustomerID: Paddle ID of the customer that this payment method is saved for, prefixed with `ctm_`.
	CustomerID string `json:"customer_id"`
	// AddressID: Paddle ID of the address for this payment method, prefixed with `add_`.
	AddressID string `json:"address_id"`
	// DeletionReason: Reason why this payment method was deleted.
	DeletionReason PaymentMethodDeletionReason `json:"deletion_reason"`
	// Type: Type of payment method saved.
	Type SavedPaymentMethodType `json:"type"`
	// Origin: Describes how this payment method was saved.
	Origin PaymentMethodOrigin `json:"origin"`
	// SavedAt: RFC 3339 datetime string of when this entity was saved. Set automatically by Paddle.
	SavedAt string `json:"saved_at"`
	// UpdatedAt: RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
	UpdatedAt string `json:"updated_at"`
}
