// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// ReportCreated represents the report.created event.
// See https://developer.paddle.com/webhooks/overview for more information.
type ReportCreated struct {
	GenericNotificationsEvent
	Data ReportNotification `json:"data"`
}

// ReportUpdated represents the report.updated event.
// See https://developer.paddle.com/webhooks/overview for more information.
type ReportUpdated struct {
	GenericNotificationsEvent
	Data ReportNotification `json:"data"`
}

/*
ReportStatus: Status of this report. Set automatically by Paddle.

Reports are created as `pending` initially, then move to `ready` when they're available to download..
*/
type ReportStatus string

const (
	ReportStatusPending = "pending"
	ReportStatusReady   = "ready"
	ReportStatusFailed  = "failed"
	ReportStatusExpired = "expired"
)

// ReportTypeTransactions: Type of report..
type ReportTypeTransactions string

const (
	ReportTypeTransactionsAdjustments          = "adjustments"
	ReportTypeTransactionsAdjustmentLineItems  = "adjustment_line_items"
	ReportTypeTransactionsTransactions         = "transactions"
	ReportTypeTransactionsTransactionLineItems = "transaction_line_items"
	ReportTypeTransactionsProductsPrices       = "products_prices"
	ReportTypeTransactionsDiscounts            = "discounts"
)

// Name: Field name to filter by..
type ReportsName string

const (
	ReportsNameAction           = "action"
	ReportsNameCurrencyCode     = "currency_code"
	ReportsNameStatus           = "status"
	ReportsNameUpdatedAt        = "updated_at"
	ReportsNameCollectionMode   = "collection_mode"
	ReportsNameOrigin           = "origin"
	ReportsNameProductStatus    = "product_status"
	ReportsNamePriceStatus      = "price_status"
	ReportsNameProductType      = "product_type"
	ReportsNamePriceType        = "price_type"
	ReportsNameProductUpdatedAt = "product_updated_at"
	ReportsNamePriceUpdatedAt   = "price_updated_at"
	ReportsNameType             = "type"
)

// Operator: Operator to use when filtering. Valid when filtering by `updated_at`, `null` otherwise..
type ReportsOperator *string

const (
	ReportsOperatorLt  = "lt"
	ReportsOperatorGte = "gte"
)

// ReportFilters: List of filters applied to this report.
type ReportFilters struct {
	// Name: Field name to filter by.
	Name string `json:"name,omitempty"`
	// Operator: Operator to use when filtering. Valid when filtering by `updated_at`, `null` otherwise.
	Operator *string `json:"operator,omitempty"`
	// Value: Value to filter by. Check the allowed values descriptions for the `name` field to see valid values for a field.
	Value string `json:"value,omitempty"`
}

// ReportNotification: New or changed entity.
type ReportNotification struct {
	// ID: Unique Paddle ID for this report, prefixed with `rep_`
	ID string `json:"id,omitempty"`
	/*
	   Status: Status of this report. Set automatically by Paddle.

	   Reports are created as `pending` initially, then move to `ready` when they're available to download.
	*/
	Status string `json:"status,omitempty"`
	// Rows: Number of records in this report. `null` if the report is `pending`.
	Rows *int `json:"rows,omitempty"`
	// Type: Type of report.
	Type string `json:"type,omitempty"`
	// Filters: List of filters applied to this report.
	Filters []ReportFilters `json:"filters,omitempty"`
	// ExpiresAt: RFC 3339 datetime string of when this report expires. The report is no longer available to download after this date.
	ExpiresAt *string `json:"expires_at,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of when this report was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
	// CreatedAt: RFC 3339 datetime string of when this report was created.
	CreatedAt string `json:"created_at,omitempty"`
}
