// Code generated by the Paddle SDK Generator; DO NOT EDIT.

package paddlenotification

// ReportCreated represents the report.created event.
// See https://developer.paddle.com/webhooks/overview for more information.
type ReportCreated struct {
	GenericNotificationsEvent
	Data ReportNotification `json:"data"`
}

// ReportUpdated represents the report.updated event.
// See https://developer.paddle.com/webhooks/overview for more information.
type ReportUpdated struct {
	GenericNotificationsEvent
	Data ReportNotification `json:"data"`
}

/*
ReportStatus: Status of this report. Set automatically by Paddle.

Reports are created as `pending` initially, then move to `ready` when they're available to download..
*/
type ReportStatus string

const (
	ReportStatusPending ReportStatus = "pending"
	ReportStatusReady   ReportStatus = "ready"
	ReportStatusFailed  ReportStatus = "failed"
	ReportStatusExpired ReportStatus = "expired"
)

// ReportTypeTransactions: Type of report..
type ReportTypeTransactions string

const (
	ReportTypeTransactionsAdjustments          ReportTypeTransactions = "adjustments"
	ReportTypeTransactionsAdjustmentLineItems  ReportTypeTransactions = "adjustment_line_items"
	ReportTypeTransactionsTransactions         ReportTypeTransactions = "transactions"
	ReportTypeTransactionsTransactionLineItems ReportTypeTransactions = "transaction_line_items"
	ReportTypeTransactionsProductsPrices       ReportTypeTransactions = "products_prices"
	ReportTypeTransactionsDiscounts            ReportTypeTransactions = "discounts"
)

// Name: Field name to filter by..
type ReportsName string

const (
	ReportsNameAction           ReportsName = "action"
	ReportsNameCurrencyCode     ReportsName = "currency_code"
	ReportsNameStatus           ReportsName = "status"
	ReportsNameUpdatedAt        ReportsName = "updated_at"
	ReportsNameCollectionMode   ReportsName = "collection_mode"
	ReportsNameOrigin           ReportsName = "origin"
	ReportsNameProductStatus    ReportsName = "product_status"
	ReportsNamePriceStatus      ReportsName = "price_status"
	ReportsNameProductType      ReportsName = "product_type"
	ReportsNamePriceType        ReportsName = "price_type"
	ReportsNameProductUpdatedAt ReportsName = "product_updated_at"
	ReportsNamePriceUpdatedAt   ReportsName = "price_updated_at"
	ReportsNameType             ReportsName = "type"
)

// Operator: Operator to use when filtering. Valid when filtering by `updated_at`, `null` otherwise..
type ReportsOperator string

const (
	ReportsOperatorLt  ReportsOperator = "lt"
	ReportsOperatorGte ReportsOperator = "gte"
)

// ReportFilters: List of filters applied to this report.
type ReportFilters struct {
	// Name: Field name to filter by.
	Name ReportsName `json:"name,omitempty"`
	// Operator: Operator to use when filtering. Valid when filtering by `updated_at`, `null` otherwise.
	Operator *ReportsOperator `json:"operator,omitempty"`
	// Value: Value to filter by. Check the allowed values descriptions for the `name` field to see valid values for a field.
	Value string `json:"value,omitempty"`
}

// ReportNotification: New or changed entity.
type ReportNotification struct {
	// ID: Unique Paddle ID for this report, prefixed with `rep_`
	ID string `json:"id,omitempty"`
	/*
	   Status: Status of this report. Set automatically by Paddle.

	   Reports are created as `pending` initially, then move to `ready` when they're available to download.
	*/
	Status ReportStatus `json:"status,omitempty"`
	// Rows: Number of records in this report. `null` if the report is `pending`.
	Rows *int `json:"rows,omitempty"`
	// Type: Type of report.
	Type ReportTypeTransactions `json:"type,omitempty"`
	// Filters: List of filters applied to this report.
	Filters []ReportFilters `json:"filters,omitempty"`
	// ExpiresAt: RFC 3339 datetime string of when this report expires. The report is no longer available to download after this date.
	ExpiresAt *string `json:"expires_at,omitempty"`
	// UpdatedAt: RFC 3339 datetime string of when this report was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
	// CreatedAt: RFC 3339 datetime string of when this report was created.
	CreatedAt string `json:"created_at,omitempty"`
}
